flask
gunicorn
hyperopt
matplotlib
numpy
pandas
pandas-flavor
pip
#torch
#pytorch
rdkit
scikit-learn
scipy
tensorboardX
#torchvision
tqdm
#cudatoolkit
tensorflow-rocm
#tensorflow
#torchaudio
typed-argument-parser
git+https://github.com/bp-kelley/descriptastorus
file:///opt/chemprop-1.3.1_mod.tar.gz
