#!/bin/bash
#SBATCH --partition=small
#SBATCH --nodes=1
#SBATCH --ntasks=40
#SBATCH --cpus-per-task=1 # 40
#SBATCH --time=15:10:10 # 40:00:00
#SBATCH --account=project_2001659

module load maestro parallel

find $PWD/data_SMILES2/splits  -name '*.smi' | \
parallel -j 38 bash ${SLURM_SUBMIT_DIR}/wrapper_ligprep_pipeline.sh {} 
